# Generated by Django 3.1.6 on 2021-03-24 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admindashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallLogEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.CharField(blank=True, max_length=255, null=True)),
                ('cid', models.CharField(blank=True, max_length=255, null=True)),
                ('cid_e164', models.CharField(blank=True, max_length=255, null=True)),
                ('called_number', models.CharField(blank=True, max_length=255, null=True)),
                ('event', models.CharField(blank=True, max_length=255, null=True)),
                ('data', models.CharField(blank=True, max_length=255, null=True)),
                ('callduration', models.CharField(blank=True, max_length=255, null=True)),
                ('record_duration', models.CharField(blank=True, max_length=255, null=True)),
                ('total_call_duration', models.CharField(blank=True, max_length=255, null=True)),
                ('process', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('telco_code', models.CharField(blank=True, max_length=255, null=True)),
                ('outbound_sid', models.CharField(blank=True, max_length=255, null=True)),
                ('circle', models.CharField(blank=True, max_length=255, null=True)),
                ('operator', models.CharField(blank=True, max_length=255, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('call_sid', models.CharField(max_length=255, null=True)),
                ('account_sid', models.CharField(max_length=255, null=True)),
                ('from_number', models.CharField(max_length=255, null=True)),
                ('to_number', models.CharField(max_length=255, null=True)),
                ('call_status', models.CharField(max_length=255, null=True)),
                ('direction', models.CharField(max_length=255, null=True)),
                ('parent_call_sid', models.CharField(max_length=255, null=True)),
                ('telco_status', models.CharField(max_length=255, null=True)),
                ('dial_time', models.CharField(max_length=255, null=True)),
                ('pick_time', models.CharField(max_length=255, null=True)),
                ('end_time', models.CharField(max_length=255, null=True)),
                ('duration', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='ivrprompt',
            name='keypress',
            field=models.SmallIntegerField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ivrpromptresponse',
            name='keypress',
            field=models.SmallIntegerField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='calllog',
            name='call_type',
            field=models.CharField(choices=[('Inbound Call', 'Inbound Call'), ('Outbound Call', 'Outbound Call'), ('Inbound Missedcall', 'Inbound Missedcall'), ('Outbound Live Call', 'Outbound Live Call')], max_length=50),
        ),
        migrations.AlterField(
            model_name='calllog',
            name='status',
            field=models.CharField(choices=[('No Response', 'No Response'), ('Unreachable', 'Unreachable'), ('DND', 'DND'), ('Invalid Number', 'Invalid Number'), ('Rejected', 'Rejected'), ('Busy', 'Busy'), ('Answered', 'Answered')], max_length=50),
        ),
        migrations.AlterField(
            model_name='content',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=50),
        ),
        migrations.AlterField(
            model_name='ivrprompt',
            name='status',
            field=models.CharField(choices=[('Active', 'active'), ('Inactive', 'inactive')], default='Active', max_length=50),
        ),
        migrations.AlterField(
            model_name='partnersystemphone',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=50),
        ),
        migrations.AlterField(
            model_name='program',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=50),
        ),
        migrations.AlterField(
            model_name='registration',
            name='parent_type',
            field=models.CharField(choices=[('Father', 'Father'), ('Mother', 'Mother'), ('Grand Father', 'Grand Father'), ('Grand Mother', 'Grand Mother'), ('Other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='registration',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In-Progress', 'In-Progress'), ('Complete', 'Complete')], default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='systemphone',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='usermodulecontent',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In-Progress', 'In-Progress'), ('Complete', 'Complete')], default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprogram',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=50),
        ),
    ]
